version: "3.7"
services:
  web:
    image: asbiamrullah19/web-custom
    depends_on: 
    - mysql
  mysql:
    image: mysql:5.7
  proxy:
    image: asbiamrullah19/proxy-custom
    depends_on:
    - web
  pma:
    image: phpmyadmin:latest
    depends_on:
      - mysql