version: "3.7"
services:
  web:
    build: .
    working_dir: /var/www/html
    volumes:
       - ./file-web:/var/www/html/
    networks:
      proxy_net:
      int_net:
    healthcheck:
      test: curl -f http://localhost/ || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  mysql:
    secrets:
      - root
      - database
      - user
      - password   
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root
      MYSQL_DATABASE_FILE : /run/secrets/database
      MYSQL_USER_FILE : /run/secrets/user
      MYSQL_PASSWORD_FILE : /run/secrets/password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      proxy_net:
      int_net:
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120

  proxy:
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      proxy_net:
    healthcheck:
      test: curl -f http://localhost/ || exit 0
      interval: 5s
      timeout: 10s
      retries: 3

  pma:
    environment:
      PMA_HOSTS : mysql
    networks:
      int_net:
      proxy_net:
    healthcheck:
      test: curl -f http://pma:80/ || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  mysql-data:
  pma-data:
networks:
  proxy_net:
  int_net:
    
secrets:
 root:
  file: ./secret/root.txt
 database:
  file: ./secret/database.txt
 user:
  file: ./secret/user.txt
 password:
  file: ./secret/password.txt
